In [2]:
import pandas as pd
import os

In [7]:
data=pd.read_csv(os.getcwd()+'/data/xrzct.csv')
data.drop(['Comment'],axis=1,inplace=True)

In [8]:
data.head()

   section  Trace   Length  Area  Unnamed: 5
0        1  calX1  4.61062   0.0         NaN
1        1  calX2  4.57787   0.0         NaN
2        1  calX3  4.60833   0.0         NaN
3        1  calX4  4.59057   0.0         NaN
4        1  calX5  4.59153   0.0         NaN

In [9]:
data['DendriteID'] = data['Trace'].astype(str).str[0:4]

In [12]:
data['SynapseID'] = data['Trace'].astype(str).str[5:]

In [14]:
data

,section,Trace,Length,Area,Unnamed: 5,DendriteID,SynapseID
0,1,calX1,4.610620,0.000000,NaN,calX,
1,1,calX2,4.577870,0.000000,NaN,calX,
2,1,calX3,4.608330,0.000000,NaN,calX,
3,1,calX4,4.590570,0.000000,NaN,calX,
4,1,calX5,4.591530,0.000000,NaN,calX,
5,1,calY1,4.638200,0.000000,NaN,calY,
6,1,calY2,4.626350,0.000000,NaN,calY,
7,1,calY3,4.703720,0.000000,NaN,calY,
8,1,calY4,4.660380,0.000000,NaN,calY,
9,1,calY5,4.692420,0.000000,NaN,calY,
10,2,d001,1.065370,0.084306,NaN,d001,
11,2,d001_c01,0.688887,0.028214,NaN,d001,c01
12,2,d001_c02,0.786678,0.032260,NaN,d001,c02
13,2,d001_cfa01,0.244925,0.000000,NaN,d001,cfa01
14,2,d001_cfa02,0.253807,0.000000,NaN,d001,cfa02
15,2,d002,2.776920,0.571535,NaN,d002,
16,2,d002_c01,1.170650,0.072173,NaN,d002,c01
17,2,d002_c02,1.743520,0.102787,NaN,d002,c02
18,2,d002_c02_DSV1,0.065379,0.000052,NaN,d002,c02_DSV1
19,2,d002_c02_DSV2,0.065379,0.000052,NaN,d002,c02_DSV2
20,2,d002_c04_SV599,0.077416,0.000074,NaN,d002,c04_SV599
21,2,d002_c04_SV600,0.077416,0.000074,NaN,d002,c04_SV600
22,2,d002_c04_SV601,0.077591,0.000073,NaN,d002,c04_SV601
23,2,d002_c04_SV602,0.077432,0.000074,NaN,d002,c04_SV602
24,2,d002_c04_SV603,0.077540,0.000074,NaN,d002,c04_SV603
25,2,d002_c04_SV604,0.077455,0.000074,NaN,d002,c04_SV604
26,2,d002_c04_SV605,0.077384,0.000074,NaN,d002,c04_SV605
27,2,d002_c04_SV606,0.077189,0.000074,NaN,d002,c04_SV606
28,2,d002_c04_SV607,0.077214,0.000074,NaN,d002,c04_SV607
29,2,d002_c04_SV608,0.077455,0.000074,NaN,d002,c04_SV608
...,...,...,...,...,...,...,...
15829,205,d011_c16,1.173050,0.030643,NaN,d011,c16
15830,205,d011_cfa16,0.422002,0.000000,NaN,d011,cfa16
15831,205,d011_mito01,0.506720,0.009487,NaN,d011,mito01
15832,205,d012,3.709270,0.547839,NaN,d012,
15833,205,d012_c29,1.371740,0.036524,NaN,d012,c29
15834,205,d012_c31,0.822156,0.013968,NaN,d012,c31
15835,205,d012_c32,0.692064,0.028437,NaN,d012,c32
15836,205,d012_cfa29,0.571263,0.000000,NaN,d012,cfa29
15837,205,d012_cfa31,0.382259,0.000000,NaN,d012,cfa31
15838,205,d012_cfa32,0.133336,0.000000,NaN,d012,cfa32
15839,205,d012_mito05,1.679130,0.066633,NaN,d012,mito05
15840,205,d012_mito05,0.999193,0.055625,NaN,d012,mito05
15841,205,d014,2.437390,0.266195,NaN,d014,
15842,205,d014_c24,0.728014,0.027549,NaN,d014,c24
15843,205,d014_cfa24,0.163259,0.000000,NaN,d014,cfa24
15844,205,d014_mito03,0.570468,0.013745,NaN,d014,mito03
15845,205,d014_mito04,0.765250,0.020544,NaN,d014,mito04
15846,205,d015,2.304440,0.213424,NaN,d015,
15847,205,d015_mito02,0.665790,0.017368,NaN,d015,mito02
15848,205,d017,2.578970,0.167447,NaN,d017,
15849,205,d020,1.539220,0.096478,NaN,d020,
15850,205,d020_c40,1.020370,0.023681,NaN,d020,c40
15851,205,d020_cfa40,0.368431,0.000000,NaN,d020,cfa40
15852,205,d020_mito06,0.701034,0.019817,NaN,d020,mito06
15853,205,diameter20,0.559396,0.000000,NaN,diam,ter20
15854,205,diameter20,0.216565,0.000000,NaN,diam,ter20
15855,205,diameter20,0.699797,0.000000,NaN,diam,ter20
15856,205,diameter4,0.738823,0.000000,NaN,diam,ter4
15857,205,diameter4,0.258954,0.000000,NaN,diam,ter4
15858,205,diameter4,1.004680,0.000000,NaN,diam,ter4

In [16]:
data.to_csv(os.getcwd()+'/data/xrzctBenParse.csv')

In [22]:
datasumarea=data.groupby(['DendriteID']).sum()['Area']

In [23]:
datasumarea.to_csv(os.getcwd()+'/data/xrzctBenParseSumAreaBySyn.csv')

In [25]:
datasumarea

DendriteID
NOT       0.246767
calX      0.000000
calY      0.000000
cyan      0.000000
d001     33.311000
d002    231.755247
d003    258.455893
d004    150.432372
d005    151.755397
d006     43.632401
d007      5.914775
d008     53.730809
d009     86.219924
d010     48.037969
d011     44.957584
d012     64.810209
d013      1.804427
d014     61.340938
d015     68.520742
d016      0.303137
d017     11.049614
d019      0.216206
d020     96.310443
d02c      0.070910
diam      0.000000
mayb      0.564082
mito      0.000000
pr?       0.000113
spin      0.348086
Name: Area, dtype: float64